name       : haskell-base64-bytestring
version    : 1.0.0.1
release    : 2
source     :
    - http://hackage.haskell.org/package/base64-bytestring-1.0.0.1/base64-bytestring-1.0.0.1.tar.gz : ab25abf4b00a2f52b270bc3ed43f1d59f16c8eec9d7dffb14df1e9265b233b50
license    : BSD-3-Clause
component  : programming
summary    : Fast base64 encoding and decoding for ByteStrings
description: |
    Fast base64 encoding and decoding for ByteStrings
builddeps  :
    - ghc
setup      : |
    ghc -threaded Setup
    ./Setup configure --enable-shared \
                      --prefix=/usr \
                      --docdir="/usr/share/doc/\$compiler/\$pkgid" \
                      --libdir=/usr/lib64 \
                      --libsubdir="\$compiler/\$pkgid" \
                      --datadir=/usr/share \
                      --sysconfdir=/etc
build      : |
    ./Setup build
install    : |
    export GHCV=`readlink /usr/bin/ghc`
    ./Setup copy --destdir=$installdir
    ./Setup register --gen-pkg-config
    install -D -m 00644 base64-bytestring-$version.conf $installdir/usr/lib64/$GHCV/package.conf.d/base64-bytestring-$version.conf
