name       : haskell-base64-bytestring
version    : 1.2.1.0
release    : 7
source     :
    - https://hackage.haskell.org/package/base64-bytestring-1.2.1.0/base64-bytestring-1.2.1.0.tar.gz : fbf8ed30edde271eb605352021431d8f1b055f95a56af31fe2eacf6bdfdc49c9
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast base64 encoding and decoding for ByteStrings
description: |
    Fast base64 encoding and decoding for ByteStrings
builddeps  :
    - ghc-devel
setup      : |
    %haskell_configure
build      : |
    %haskell_build
install    : |
    %haskell_install
    %haskell_register
