name       : haskell-base64-bytestring
version    : 1.0.0.1
release    : 5
source     :
    - http://hackage.haskell.org/package/base64-bytestring-1.0.0.1/base64-bytestring-1.0.0.1.tar.gz : ab25abf4b00a2f52b270bc3ed43f1d59f16c8eec9d7dffb14df1e9265b233b50
license    : BSD-3-Clause
component  : programming.haskell
summary    : Fast base64 encoding and decoding for ByteStrings
description: |
    Fast base64 encoding and decoding for ByteStrings
builddeps  :
    - ghc
    - haskell-cabal-install
setup      : |
    %cabal_configure
build      : |
    %cabal_build
install    : |
    %cabal_install
    %cabal_register
